// <auto-generated />
namespace Akelote_e_Shop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _2018050521213 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_2018050521213));
        
        string IMigrationMetadata.Id
        {
            get { return "201805051821383_2018050521213"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
